"""submissions modify date

Revision ID: 0efc7b45503d
Revises: 
Create Date: 2024-06-16 14:39:26.620911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efc7b45503d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_date_str', sa.String(), nullable=False))
        batch_op.alter_column('assignment_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('assignment_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_column('submission_date_str')

    # ### end Alembic commands ###
